apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-07-14T18:03:39Z"
  generation: 1
  labels:
    app: test-image
  name: test-image
  namespace: default
  resourceVersion: "795"
  uid: a062be56-4a08-4be2-bebb-12e94f1904d2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-image
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-image
    spec:
      containers:
      - image: applicationimage:v1
        imagePullPolicy: IfNotPresent
        name: applicationimage
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-07-14T18:03:40Z"
    lastUpdateTime: "2021-07-14T18:03:40Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-07-14T18:03:39Z"
    lastUpdateTime: "2021-07-14T18:03:40Z"
    message: ReplicaSet "test-image-69796cc8ff" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
