apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: filebeat-1626319673
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-07-15T03:27:56Z"
  labels:
    app: filebeat-1626319673-filebeat
    app.kubernetes.io/managed-by: Helm
    chart: filebeat-7.13.2
    heritage: Helm
    release: filebeat-1626319673
  name: filebeat-1626319673-filebeat
  namespace: default
  resourceVersion: "14910"
  uid: f0cf5eb6-49d6-4481-8d0b-d756de7acf3b
secrets:
- name: filebeat-1626319673-filebeat-token-d5r9b
