apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: grafana-1626315024
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-07-15T02:10:28Z"
  labels:
    app.kubernetes.io/instance: grafana-1626315024
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 7.1.1
    helm.sh/chart: grafana-5.5.7
  name: grafana-1626315024
  namespace: default
  resourceVersion: "10851"
  uid: f0fc9355-0cfd-42ea-baea-c49a960630c1
secrets:
- name: grafana-1626315024-token-s2xks
