apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus-1626313483
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-07-15T01:44:48Z"
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-11.12.1
    component: server
    heritage: Helm
    release: prometheus-1626313483
  name: prometheus-1626313483-server
  namespace: default
  resourceVersion: "9559"
  uid: cc3b2c2f-3314-4db3-b7cf-fbb4e15ea56c
secrets:
- name: prometheus-1626313483-server-token-6s6pf
