apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
  creationTimestamp: "2021-07-14T19:30:47Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: elasticsearch-master
  name: elasticsearch-master-elasticsearch-master-1
  namespace: default
  resourceVersion: "5838"
  uid: 03ce6e26-117a-48dd-87e5-c5852b018fb2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-03ce6e26-117a-48dd-87e5-c5852b018fb2
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100M
  phase: Bound
