apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
  creationTimestamp: "2021-07-15T04:26:44Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: elasticsearch-master
  name: elasticsearch-master-elasticsearch-master-1
  namespace: default
  resourceVersion: "17949"
  uid: 27b2474e-1a2e-4575-ab19-d7a3413da1e8
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-27b2474e-1a2e-4575-ab19-d7a3413da1e8
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100M
  phase: Bound
