apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: elasticsearch-1626291043
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-07-14T19:30:46Z"
  labels:
    app: elasticsearch-master
    app.kubernetes.io/managed-by: Helm
    chart: elasticsearch
    heritage: Helm
    release: elasticsearch-1626291043
  name: elasticsearch-master
  namespace: default
  resourceVersion: "5787"
  uid: 447355d0-2264-4ac4-b6d2-60121b4c1b2d
spec:
  clusterIP: 10.100.105.165
  clusterIPs:
  - 10.100.105.165
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: transport
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    app: elasticsearch-master
    chart: elasticsearch
    release: elasticsearch-1626291043
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
