apiVersion: v1
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/"

    output.elasticsearch:
      host: '${NODE_NAME}'
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: filebeat-1626319673
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-07-15T03:27:56Z"
  labels:
    app: filebeat-1626319673-filebeat
    app.kubernetes.io/managed-by: Helm
    chart: filebeat-7.13.2
    heritage: Helm
    release: filebeat-1626319673
  name: filebeat-1626319673-filebeat-daemonset-config
  namespace: default
  resourceVersion: "14906"
  uid: e02db0be-2738-4e4e-a0f9-6e982f5d2792
