apiVersion: v1
data:
  alertmanager.yml: |
    global: {}
    receivers:
    - name: default-receiver
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: default-receiver
      repeat_interval: 3h
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus-1626313483
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-07-15T01:44:48Z"
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-11.12.1
    component: alertmanager
    heritage: Helm
    release: prometheus-1626313483
  name: prometheus-1626313483-alertmanager
  namespace: default
  resourceVersion: "9551"
  uid: 2cd10c2e-a9a6-4506-991c-95a15a13b09b
